# -*- coding: utf-8 -*-
"""Data_scraper.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1IhxEfq5jzFVmRuorHdkZQ9F-PYV5C7WP
"""

import time
from webdriver_manager.chrome import ChromeDriverManager
from selenium import webdriver
from selenium.webdriver.common.by import By
#import org.openqa.selenium.support.ui.Select;
#import selenium.webdriver.support.select
from selenium.webdriver.support.ui import Select
from selenium.webdriver.support.ui import WebDriverWait
from selenium.webdriver.support import expected_conditions as EC
from datetime import datetime

driver = webdriver.Chrome()

#directing to the website to fetch data
driver.get("https://data.cityofnewyork.us/City-Government/Parking-Violations-Issued-Fiscal-Year-2023/pvqr-7yc4")

#clicking on view data
driver.find_element(By.LINK_TEXT,'View Data').click()
time.sleep(4)

driver.find_element(By.XPATH,"//button[normalize-space()='Export']//span[@class='forge-button__ripple']").click()
time.sleep(4)

